name: draft_positions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - requests
  - pip
  - pip:
      - nfl_data_py
      - beautifulsoup4
